M48
; DRILL file {KiCad (6.0.8)} date Sat Jan 21 17:58:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-21T17:58:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X5.2756Y-3.5827
X5.4724Y-3.5039
X5.4724Y-4.1339
X5.6693Y-3.622
X6.2992Y-3.5827
T0
M30
